# Generated by Django 5.0.4 on 2024-04-10 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_company_options_alter_vacancy_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterUniqueTogether(
            name='company',
            unique_together=set(),
        ),
        migrations.AlterIndexTogether(
            name='company',
            index_together=set(),
        ),
        migrations.AlterModelTable(
            name='company',
            table=None,
        ),
    ]
