# Generated by Django 5.0.4 on 2024-04-11 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_vacancy_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
    ]
