# Generated by Django 4.2.20 on 2025-04-11 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_category_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AlterModelOptions(
            name='vacancy',
            options={},
        ),
    ]
